# Importing the libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset

In [2]:
ds = pd.read_csv('Data.csv')

In [3]:
X = ds.iloc[:,:-1].values
y = ds.iloc[:, -1].values

In [4]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [5]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


# Taking care of missing data

In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
X[:, 1:3] = imputer.fit_transform(X[:, 1:3])

In [7]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


# Encoding Categorical Data

## Encoding the independent Variable

In [8]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le_X = LabelEncoder()
X[:,0] = le_X.fit_transform(X[:,0])

In [9]:
print(X)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 63777.77777777778]
 [0 35.0 58000.0]
 [2 38.77777777777778 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [10]:
ohe_X = OneHotEncoder(categorical_features = [0])
X = ohe_X.fit_transform(X).toarray()

/Users/mohitgoel/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/Users/mohitgoel/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [11]:
X.shape

(10, 5)

## Avoiding the dummy variable trap

In [12]:
X = X[:,1:]

In [13]:
X.shape

(10, 4)

## Encoding the dependent variable

In [14]:
le_y = LabelEncoder()
y = le_y.fit_transform(y)

In [15]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Splitting the dataset into the training set and test set

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [29]:
print(X)

[[0.00000000e+00 0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [0.00000000e+00 1.00000000e+00 2.70000000e+01 4.80000000e+04]
 [1.00000000e+00 0.00000000e+00 3.00000000e+01 5.40000000e+04]
 [0.00000000e+00 1.00000000e+00 3.80000000e+01 6.10000000e+04]
 [1.00000000e+00 0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [0.00000000e+00 0.00000000e+00 3.50000000e+01 5.80000000e+04]
 [0.00000000e+00 1.00000000e+00 3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 0.00000000e+00 4.80000000e+01 7.90000000e+04]
 [1.00000000e+00 0.00000000e+00 5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 0.00000000e+00 3.70000000e+01 6.70000000e+04]]


In [30]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


# Feature Scaling

In [31]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train[:, 2:] = sc_X.fit_transform(X_train[:, 2:])
X_test[:, 2:] = sc_X.transform(X_test[:, 2:])

In [32]:
print(X_train)

[[ 1.          0.          0.26306757  0.12381479]
 [ 0.          0.         -0.25350148  0.46175632]
 [ 0.          1.         -1.97539832 -1.53093341]
 [ 0.          1.          0.05261351 -1.11141978]
 [ 0.          0.          1.64058505  1.7202972 ]
 [ 0.          1.         -0.0813118  -0.16751412]
 [ 0.          0.          0.95182631  0.98614835]
 [ 0.          0.         -0.59788085 -0.48214934]]


In [33]:
print(X_test)

[[ 1.          0.         -1.45882927 -0.90166297]
 [ 1.          0.          1.98496442  2.13981082]]
